### ISSUE TITLE
Improvements for DeviceInfoMiddleware

### ISSUE THREAD

**Issue by sanchezzzhak** [missaelx/url_shrinker#1]
Hi, Senor.

https://github.com/missaelx/url_shrinker/blob/dbe38647500dc6860861401a2d310684d98b51a6/src/node/middleware/DeviceInfoMiddleware.js#L4

you need to move the initialization of the class higher, this improves performance.
```js
import DeviceDetector from "node-device-detector";

const detector = new DeviceDetector;

export default (req, res, next) => {
    let userAgent = req.headers['user-agent'];
    req.deviceInfo = detector.detect(userAgent);
    next();
}
```
The fact is that when the detector is initialized, all data is loaded from YML files

**Comment by missaelx** [comment]
Hi,
Thanks for pointing me out this. Already fixed it.
Have a good weekend

ps. Thanks for the library
